import { useState } from 'react';  // ← YEH IMPORT ADD KAREIN

// ===== LANGUAGE TRANSLATIONS =====
export const translations = {
  en: {
    home: 'Home',
    products: 'Products',
    wishlist: 'Wishlist',
    cart: 'Cart',
    wallet: 'Wallet',
    admin: 'Admin',
    dashboard: 'Dashboard',
    profile: 'Profile',
    orders: 'Orders',
    track: 'Track',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    getStarted: 'Get Started',
    guest: 'Guest',
    shopApp: '✦ ShopApp',
    search: 'Search',
    addToCart: 'Add to Cart',
    total: 'Total',
    placeOrder: 'Place Order',
    checkout: 'Checkout',
    orderSummary: 'Order Summary',
    items: 'Items',
    noOrders: 'No orders yet',
    startShopping: 'Start Shopping',
    welcomeBack: 'Welcome back',
    youHave: 'You have',
    ordersCount: 'orders',
    loading: 'Loading...',
    refresh: 'Refresh',
    myWallet: 'My Wallet',
    availableBalance: 'Available Balance',
    totalDeposits: 'Total Deposits',
    transactions: 'Transactions',
    addMoney: 'Add Money',
    topUp: 'Top Up',
    history: 'History',
    quickSelect: 'Quick Select Amount',
    customAmount: 'Custom Amount',
    enterAmount: 'Enter amount (min Rs. 100)',
    topUpNow: 'Top Up Now',
    balance: 'Balance',
    noTransactions: 'No transactions yet',
    paymentMethod: 'Payment Method',
    card: 'Card',
    easypaisa: 'EasyPaisa',
    jazzcash: 'JazzCash',
    cardNumber: 'Card Number',
    cardHolder: 'Card Holder Name',
    expiry: 'Expiry Date',
    cvv: 'CVV',
    payNow: 'Pay Now',
    processing: 'Processing...',
    orderId: 'Order ID',
    product: 'Product',
    date: 'Date',
    status: 'Status',
    amount: 'Amount',
    pending: 'Pending',
    shipping: 'Shipping',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    viewAll: 'View All Orders',
    editProfile: 'Edit Profile',
    save: 'Save',
    cancel: 'Cancel',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    role: 'Role',
    accountActions: 'Account Actions',
    changePassword: 'Change Password',
    notifications: 'Notifications',
    privacy: 'Privacy Settings',
    notLoggedIn: 'Not Logged In',
    pleaseLogin: 'Please login to view your profile.',
    memberSince: 'Member since',
    productList: 'Product List',
    ourCollection: 'Our Collection',
    browseProducts: 'Browse products by category',
    productsFound: 'products found',
    noProductsFound: 'No products found',
    category: 'Category',
    allCategories: 'All Categories',
    quickLinks: 'Quick Links',
    contactUs: 'Contact Us',
    copyright: 'All rights reserved.',
    madeWith: 'Made with ❤️ in Pakistan',
    yourCart: 'Your Cart',
    cartEmpty: 'Your Cart is Empty',
    cartEmptyDesc: 'Start shopping to add items to your cart.',
    clearCart: 'Clear Cart',
    proceedToCheckout: 'Proceed to Checkout',
    totalItems: 'Items',
    totalPrice: 'Total Price',
    removedFromCart: 'removed from cart',
    cartCleared: 'Cart cleared!',
    itemAdded: 'added to cart!',
    shippingInfo: 'Shipping Information',
    continueToPayment: 'Continue to Payment →',
    back: '← Back',
    guestCheckout: 'You are checking out as a guest. Please fill your details below.',
    paymentSuccessful: 'Payment successful!',
    orderPlaced: 'Order placed successfully!',
    success: 'Success',
    error: 'Error',
    pleaseFillAll: 'Please fill all fields',
    invalidAmount: 'Please enter a valid amount',
    minAmount: 'Minimum amount is Rs. 100',
    selectPaymentMethod: 'Please select a payment method',
    fillCardDetails: 'Please fill all card details',
    fillShippingDetails: 'Please fill all shipping details!',
    orderCancelled: 'Order cancelled!',
    orderStatusUpdated: 'Order status updated',
    productDeleted: 'Product deleted!',
    productAdded: 'Product added successfully!',
    addedToWishlist: 'added to wishlist',
    removedFromWishlist: 'removed from wishlist',
  },
  ur: {
    home: 'ہوم',
    products: 'مصنوعات',
    wishlist: 'خواہش کی فہرست',
    cart: 'کارٹ',
    wallet: 'والٹ',
    admin: 'ایڈمن',
    dashboard: 'ڈیش بورڈ',
    profile: 'پروفائل',
    orders: 'آرڈرز',
    track: 'ٹریک',
    logout: 'لاگ آؤٹ',
    login: 'لاگ ان',
    register: 'رجسٹر',
    getStarted: 'شروع کریں',
    guest: 'مہمان',
    shopApp: '✦ شاپ ایپ',
    search: 'تلاش کریں',
    addToCart: 'کارٹ میں شامل کریں',
    total: 'کل',
    placeOrder: 'آرڈر دیں',
    checkout: 'چیک آؤٹ',
    orderSummary: 'آرڈر کا خلاصہ',
    items: 'آئٹمز',
    noOrders: 'ابھی کوئی آرڈر نہیں',
    startShopping: 'خریداری شروع کریں',
    welcomeBack: 'خوش آمدید',
    youHave: 'آپ کے پاس',
    ordersCount: 'آرڈرز',
    loading: 'لوڈ ہو رہا ہے...',
    refresh: 'ریفریش',
    myWallet: 'میرا والٹ',
    availableBalance: 'دستیاب بیلنس',
    totalDeposits: 'کل جمع',
    transactions: 'لین دین',
    addMoney: 'پیسے شامل کریں',
    topUp: 'ٹاپ اپ',
    history: 'تاریخ',
    quickSelect: 'فوری رقم منتخب کریں',
    customAmount: 'اپنی مرضی کی رقم',
    enterAmount: 'رقم درج کریں (کم از کم 100 روپے)',
    topUpNow: 'ابھی ٹاپ اپ کریں',
    balance: 'بیلنس',
    noTransactions: 'ابھی کوئی لین دین نہیں',
    paymentMethod: 'ادائیگی کا طریقہ',
    card: 'کارڈ',
    easypaisa: 'ایزی پیسہ',
    jazzcash: 'جاز کیش',
    cardNumber: 'کارڈ نمبر',
    cardHolder: 'کارڈ ہولڈر کا نام',
    expiry: 'میعاد ختم ہونے کی تاریخ',
    cvv: 'CVV',
    payNow: 'ادائیگی کریں',
    processing: 'پروسیس ہو رہا ہے...',
    orderId: 'آرڈر آئی ڈی',
    product: 'پروڈکٹ',
    date: 'تاریخ',
    status: 'حالت',
    amount: 'رقم',
    pending: 'زیر التوا',
    shipping: 'شپنگ',
    delivered: 'ڈلیور شدہ',
    cancelled: 'منسوخ',
    viewAll: 'تمام آرڈرز دیکھیں',
    editProfile: 'پروفائل میں ترمیم کریں',
    save: 'محفوظ کریں',
    cancel: 'منسوخ کریں',
    fullName: 'پورا نام',
    email: 'ای میل',
    phone: 'فون',
    address: 'پتہ',
    role: 'کردار',
    accountActions: 'اکاؤنٹ کی کارروائیاں',
    changePassword: 'پاس ورڈ تبدیل کریں',
    notifications: 'اطلاعات',
    privacy: 'رازداری کی ترتیبات',
    notLoggedIn: 'لاگ ان نہیں',
    pleaseLogin: 'براہ کرم اپنا پروفائل دیکھنے کے لیے لاگ ان کریں۔',
    memberSince: 'رکن از',
    productList: 'مصنوعات کی فہرست',
    ourCollection: 'ہمارا مجموعہ',
    browseProducts: 'زمرہ کے لحاظ سے مصنوعات دیکھیں',
    productsFound: 'مصنوعات مل گئیں',
    noProductsFound: 'کوئی مصنوعات نہیں ملی',
    category: 'زمرہ',
    allCategories: 'تمام زمرہ جات',
    quickLinks: 'فوری لنکس',
    contactUs: 'ہم سے رابطہ کریں',
    copyright: 'جملہ حقوق محفوظ ہیں۔',
    madeWith: 'محبت سے بنایا گیا ❤️ پاکستان میں',
    yourCart: 'آپ کی کارٹ',
    cartEmpty: 'آپ کی کارٹ خالی ہے',
    cartEmptyDesc: 'کارٹ میں اشیاء شامل کرنے کے لیے خریداری شروع کریں۔',
    clearCart: 'کارٹ صاف کریں',
    proceedToCheckout: 'چیک آؤٹ پر جائیں',
    totalItems: 'آئٹمز',
    totalPrice: 'کل قیمت',
    removedFromCart: 'کارٹ سے ہٹا دیا گیا',
    cartCleared: 'کارٹ صاف کر دی گئی!',
    itemAdded: 'کارٹ میں شامل کر دیا گیا!',
    shippingInfo: 'شپنگ کی معلومات',
    continueToPayment: 'ادائیگی کے لیے جاری رکھیں →',
    back: '← واپس',
    guestCheckout: 'آپ مہمان کے طور پر چیک آؤٹ کر رہے ہیں۔ براہ کرم اپنی تفصیلات درج کریں۔',
    paymentSuccessful: 'ادائیگی کامیاب!',
    orderPlaced: 'آرڈر کامیابی سے پلیس ہو گیا!',
    success: 'کامیاب',
    error: 'غلطی',
    pleaseFillAll: 'براہ کرم تمام فیلڈز پر کریں',
    invalidAmount: 'براہ کرم ایک درست رقم درج کریں',
    minAmount: 'کم از کم رقم 100 روپے ہے',
    selectPaymentMethod: 'براہ کرم ادائیگی کا طریقہ منتخب کریں',
    fillCardDetails: 'براہ کرم تمام کارڈ کی تفصیلات پر کریں',
    fillShippingDetails: 'براہ کرم تمام شپنگ کی تفصیلات پر کریں!',
    orderCancelled: 'آرڈر منسوخ کر دیا گیا!',
    orderStatusUpdated: 'آرڈر کی حالت اپ ڈیٹ کر دی گئی',
    productDeleted: 'پروڈکٹ حذف کر دی گئی!',
    productAdded: 'پروڈکٹ کامیابی سے شامل کر دی گئی!',
    addedToWishlist: 'خواہش کی فہرست میں شامل کر دیا گیا',
    removedFromWishlist: 'خواہش کی فہرست سے ہٹا دیا گیا',
  },
  es: {
    home: 'Inicio',
    products: 'Productos',
    wishlist: 'Lista de deseos',
    cart: 'Carrito',
    wallet: 'Billetera',
    admin: 'Administrador',
    dashboard: 'Panel',
    profile: 'Perfil',
    orders: 'Pedidos',
    track: 'Seguimiento',
    logout: 'Cerrar sesión',
    login: 'Iniciar sesión',
    register: 'Registrarse',
    getStarted: 'Comenzar',
    guest: 'Invitado',
    shopApp: '✦ ShopApp',
    search: 'Buscar',
    addToCart: 'Agregar al carrito',
    total: 'Total',
    placeOrder: 'Realizar pedido',
    checkout: 'Pagar',
    orderSummary: 'Resumen del pedido',
    items: 'Artículos',
    noOrders: 'Sin pedidos aún',
    startShopping: 'Comenzar a comprar',
    welcomeBack: 'Bienvenido de nuevo',
    youHave: 'Tienes',
    ordersCount: 'pedidos',
    loading: 'Cargando...',
    refresh: 'Actualizar',
    myWallet: 'Mi Billetera',
    availableBalance: 'Saldo disponible',
    totalDeposits: 'Depósitos totales',
    transactions: 'Transacciones',
    addMoney: 'Agregar dinero',
    topUp: 'Recargar',
    history: 'Historial',
    quickSelect: 'Cantidad rápida',
    customAmount: 'Cantidad personalizada',
    enterAmount: 'Ingrese cantidad (mínimo Rs. 100)',
    topUpNow: 'Recargar ahora',
    balance: 'Saldo',
    noTransactions: 'Sin transacciones aún',
    paymentMethod: 'Método de pago',
    card: 'Tarjeta',
    easypaisa: 'EasyPaisa',
    jazzcash: 'JazzCash',
    cardNumber: 'Número de tarjeta',
    cardHolder: 'Nombre del titular',
    expiry: 'Fecha de vencimiento',
    cvv: 'CVV',
    payNow: 'Pagar ahora',
    processing: 'Procesando...',
    orderId: 'ID del pedido',
    product: 'Producto',
    date: 'Fecha',
    status: 'Estado',
    amount: 'Monto',
    pending: 'Pendiente',
    shipping: 'Envío',
    delivered: 'Entregado',
    cancelled: 'Cancelado',
    viewAll: 'Ver todos',
    editProfile: 'Editar perfil',
    save: 'Guardar',
    cancel: 'Cancelar',
    fullName: 'Nombre completo',
    email: 'Correo',
    phone: 'Teléfono',
    address: 'Dirección',
    role: 'Rol',
    accountActions: 'Acciones de cuenta',
    changePassword: 'Cambiar contraseña',
    notifications: 'Notificaciones',
    privacy: 'Privacidad',
    notLoggedIn: 'No has iniciado sesión',
    pleaseLogin: 'Por favor inicia sesión para ver tu perfil.',
    memberSince: 'Miembro desde',
    productList: 'Lista de productos',
    ourCollection: 'Nuestra colección',
    browseProducts: 'Explora productos por categoría',
    productsFound: 'productos encontrados',
    noProductsFound: 'No se encontraron productos',
    category: 'Categoría',
    allCategories: 'Todas las categorías',
    quickLinks: 'Enlaces rápidos',
    contactUs: 'Contáctanos',
    copyright: 'Todos los derechos reservados.',
    madeWith: 'Hecho con ❤️ en Pakistán',
    yourCart: 'Tu carrito',
    cartEmpty: 'Tu carrito está vacío',
    cartEmptyDesc: 'Comienza a comprar para agregar artículos.',
    clearCart: 'Vaciar carrito',
    proceedToCheckout: 'Proceder al pago',
    totalItems: 'Artículos',
    totalPrice: 'Precio total',
    removedFromCart: 'eliminado del carrito',
    cartCleared: '¡Carrito vaciado!',
    itemAdded: '¡agregado al carrito!',
    shippingInfo: 'Información de envío',
    continueToPayment: 'Continuar al pago →',
    back: '← Volver',
    guestCheckout: 'Estás pagando como invitado. Completa tus datos.',
    paymentSuccessful: '¡Pago exitoso!',
    orderPlaced: '¡Pedido realizado con éxito!',
    success: 'Éxito',
    error: 'Error',
    pleaseFillAll: 'Por favor complete todos los campos',
    invalidAmount: 'Ingrese una cantidad válida',
    minAmount: 'La cantidad mínima es Rs. 100',
    selectPaymentMethod: 'Seleccione un método de pago',
    fillCardDetails: 'Complete los datos de la tarjeta',
    fillShippingDetails: '¡Complete los datos de envío!',
    orderCancelled: '¡Pedido cancelado!',
    orderStatusUpdated: 'Estado del pedido actualizado',
    productDeleted: '¡Producto eliminado!',
    productAdded: '¡Producto agregado!',
    addedToWishlist: 'agregado a la lista de deseos',
    removedFromWishlist: 'eliminado de la lista de deseos',
  },
  fr: {
    home: 'Accueil',
    products: 'Produits',
    wishlist: 'Liste de souhaits',
    cart: 'Panier',
    wallet: 'Portefeuille',
    admin: 'Admin',
    dashboard: 'Tableau de bord',
    profile: 'Profil',
    orders: 'Commandes',
    track: 'Suivi',
    logout: 'Déconnexion',
    login: 'Connexion',
    register: "S'inscrire",
    getStarted: 'Commencer',
    guest: 'Invité',
    shopApp: '✦ ShopApp',
    search: 'Rechercher',
    addToCart: 'Ajouter au panier',
    total: 'Total',
    placeOrder: 'Passer la commande',
    checkout: 'Paiement',
    orderSummary: 'Résumé de la commande',
    items: 'Articles',
    noOrders: 'Aucune commande',
    startShopping: 'Commencer à acheter',
    welcomeBack: 'Bon retour',
    youHave: 'Vous avez',
    ordersCount: 'commandes',
    loading: 'Chargement...',
    refresh: 'Rafraîchir',
    myWallet: 'Mon portefeuille',
    availableBalance: 'Solde disponible',
    totalDeposits: 'Total des dépôts',
    transactions: 'Transactions',
    addMoney: "Ajouter de l'argent",
    topUp: 'Recharger',
    history: 'Historique',
    quickSelect: 'Montant rapide',
    customAmount: 'Montant personnalisé',
    enterAmount: 'Entrez le montant (min Rs. 100)',
    topUpNow: 'Recharger maintenant',
    balance: 'Solde',
    noTransactions: 'Aucune transaction',
    paymentMethod: 'Méthode de paiement',
    card: 'Carte',
    easypaisa: 'EasyPaisa',
    jazzcash: 'JazzCash',
    cardNumber: 'Numéro de carte',
    cardHolder: 'Nom du titulaire',
    expiry: "Date d'expiration",
    cvv: 'CVV',
    payNow: 'Payer maintenant',
    processing: 'Traitement...',
    orderId: 'ID de commande',
    product: 'Produit',
    date: 'Date',
    status: 'Statut',
    amount: 'Montant',
    pending: 'En attente',
    shipping: 'Expédition',
    delivered: 'Livré',
    cancelled: 'Annulé',
    viewAll: 'Voir tout',
    editProfile: 'Modifier le profil',
    save: 'Enregistrer',
    cancel: 'Annuler',
    fullName: 'Nom complet',
    email: 'E-mail',
    phone: 'Téléphone',
    address: 'Adresse',
    role: 'Rôle',
    accountActions: 'Actions du compte',
    changePassword: 'Changer le mot de passe',
    notifications: 'Notifications',
    privacy: 'Confidentialité',
    notLoggedIn: 'Non connecté',
    pleaseLogin: 'Veuillez vous connecter pour voir votre profil.',
    memberSince: 'Membre depuis',
    productList: 'Liste des produits',
    ourCollection: 'Notre collection',
    browseProducts: 'Parcourir les produits par catégorie',
    productsFound: 'produits trouvés',
    noProductsFound: 'Aucun produit trouvé',
    category: 'Catégorie',
    allCategories: 'Toutes les catégories',
    quickLinks: 'Liens rapides',
    contactUs: 'Contactez-nous',
    copyright: 'Tous droits réservés.',
    madeWith: 'Fait avec ❤️ au Pakistan',
    yourCart: 'Votre panier',
    cartEmpty: 'Votre panier est vide',
    cartEmptyDesc: 'Commencez à acheter pour ajouter des articles.',
    clearCart: 'Vider le panier',
    proceedToCheckout: 'Passer au paiement',
    totalItems: 'Articles',
    totalPrice: 'Prix total',
    removedFromCart: 'retiré du panier',
    cartCleared: 'Panier vidé !',
    itemAdded: 'ajouté au panier !',
    shippingInfo: "Informations de livraison",
    continueToPayment: 'Continuer vers le paiement →',
    back: '← Retour',
    guestCheckout: 'Vous payez en tant qu\'invité. Remplissez vos coordonnées.',
    paymentSuccessful: 'Paiement réussi !',
    orderPlaced: 'Commande passée avec succès !',
    success: 'Succès',
    error: 'Erreur',
    pleaseFillAll: 'Veuillez remplir tous les champs',
    invalidAmount: 'Entrez un montant valide',
    minAmount: 'Le montant minimum est Rs. 100',
    selectPaymentMethod: 'Sélectionnez un mode de paiement',
    fillCardDetails: 'Remplissez les détails de la carte',
    fillShippingDetails: 'Remplissez les détails de livraison !',
    orderCancelled: 'Commande annulée !',
    orderStatusUpdated: 'Statut de la commande mis à jour',
    productDeleted: 'Produit supprimé !',
    productAdded: 'Produit ajouté !',
    addedToWishlist: 'ajouté à la liste de souhaits',
    removedFromWishlist: 'retiré de la liste de souhaits',
  },
};

// ===== GET TRANSLATION =====
export const getTranslation = (key, lang = 'en') => {
  const langData = translations[lang] || translations.en;
  return langData[key] || key;
};

// ===== USE LANGUAGE HOOK =====
export const useLanguage = () => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  const t = (key) => {
    return getTranslation(key, lang);
  };

  const changeLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('language', newLang);
  };

  return { lang, t, changeLanguage };
};